name:         htmx-example
version:      0.0.1.0
synopsis:     htmx-example

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >=4.11 && < 5
- blaze-html
- blaze-markup
- bytestring
- containers
- protolude
- safe-exceptions
- scotty
- stm
- text
- wai
- wai-cors
- wai-extra

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:         *exe-ghc-options
    dependencies:
      - htmx-example
